### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by shanfenglan** [chibd2000/hyscan#1]
![image](https://user-images.githubusercontent.com/49781523/150899678-75796cf6-c3ed-4459-afbd-c28c0c40fe77.png)

**Comment by chibd2000** [comment]
我的环境是VS2013的 编译是没问题的，警告一般是不影响编译的

C4101 "i"为引用的局部变量，你鼠标双击过去将 定义"i"变量的语句 删掉就好了

剩下的C4244和C4309参考 https://blog.csdn.net/HAX001/article/details/84101574 屏蔽警告就可以了

1.右键项目=>属性=>配置属性=>C/C++=>高级=>禁用特定警告=>4244和4309（添加数字应用确定即可）

**Comment by shanfenglan** [comment]
> 我的环境是VS2013的 编译是没问题的，警告一般是不影响编译的
> 
> C4101 "i"为引用的局部变量，你鼠标双击过去将 定义"i"变量的语句 删掉就好了
> 
> 剩下的C4244和C4309参考 https://blog.csdn.net/HAX001/article/details/84101574 屏蔽警告就可以了
> 
> 1.右键项目=>属性=>配置属性=>C/C++=>高级=>禁用特定警告=>4244和4309（添加数字应用确定即可）

问题已经解决了，需要将vs设置成拒绝sdk检查即可。
